apiVersion: k0s.k0sproject.io/v1beta1
kind: clusterconfig
spec:
  extensions:
    helm:
      concurrencyLevel: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: hello
    image: nginx:alpine
    ports:
    - containerPort: 80
