name: Lint (actionlint)
on:
  pull_request:
    paths:
      - .github/**

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true
          level: warning
          github_token: ${{ github.token }}
