name: Lint (actionlint)
on:
  pull_request:
    paths:
      - .github/**

permissions:
  contents: read
  # reviewdog's default reporter is github-pr-check, which posts a check run
  checks: write

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: reviewdog/action-actionlint@8b682e1e7e512151d73a6b9449cbff173846226e # v1.74.0
        with:
          fail_on_error: true
          level: warning
          github_token: ${{ github.token }}
