name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to write releases
      packages: write # needed for ghcr access
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
      - name: Tag name
        id: tag-name
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
        with:
          driver: docker-container

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Build binaries
        id: build_bins
        env:
          TAG_NAME: ${{ steps.tag-name.outputs.tag }}
        run: make build-all

      - name: Create release and upload binaries
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/k0sctl-*
            bin/checksums.txt
          body_path: bin/checksums.md
          tag_name: ${{ steps.tag-name.outputs.tag }}
          name: ${{ steps.tag-name.outputs.tag }}
          draft: true # So we can manually edit before publishing
          prerelease: ${{ contains(steps.tag-name.outputs.tag, '-') }} # v0.1.2-beta1, 1.2.3-rc1

      - name: Build image and push to GitHub image registry
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/riscv64
          tags: |
            ghcr.io/k0sproject/k0sctl:latest
            ghcr.io/k0sproject/k0sctl:${{ steps.tag-name.outputs.tag }}
          push: true
